M3Light/Controllers/CoreController.cs
using M3Light.Logic;
using M3Light.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;


namespace M3Light.Controllers {
    public class CoreController : Controller {
        #region dependencies
        GridLogic gridLogic = new GridLogic();
        MenuLogic menuLogic = new MenuLogic();
        #endregion

        [HttpGet]
        public void Export (string sessionName) {
            #region Parâmetros globais que devem ser validados em todos os menus
            if (Session[CacheSystem.SessionNameUsername] == null || Session[CacheSystem.SessionNameMenus] == null ||
                Session[CacheSystem.SessionNameMenuID] == null || Session[CacheSystem.SessionNameAllData] == null) {
                RedirectToAction("Index", "Login");
                return;
            }
            #endregion

            if (sessionName == null || Session[sessionName] == null) {
                return;
            }

            var sessionData = ((AllDataModel)Session[sessionName]);
            var workbook = gridLogic.Export(sessionData.Data, sessionData.ColumnsToShow);

            var fileName = string.Format("M3Light_{0}.xlsx", DateTime.Now.ToString("yyyyMMddHHmmss"));

            using (var exportData = new MemoryStream()) {
                Response.Clear();
                workbook.Write(exportData);
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("Content-Disposition", string.Format("attachment;filename={0}", fileName));
                Response.BinaryWrite(exportData.ToArray());
                Response.End();
            }
        }

        public ActionResult ProcessDataMenu (int menuID = 0, int page = 1, string sort = "", string sortDir = "", bool refreshData = false, string filters = "", string requiredFilters = "", string addColumns = "", bool isSubMenu = false) {
            #region SessionsCheck
            if (Session[CacheSystem.SessionNameUsername] == null ||
                Session[CacheSystem.SessionNameMenus] == null ||
                (Session[CacheSystem.SessionNameMenuID] == null && menuID == 0)) {
                return RedirectToAction("Index", "Login");
            }

            var cleanFilters = false;

            if (menuID == 0 && Session[CacheSystem.SessionNameMenuID] != null) {
                menuID = int.Parse(Session[CacheSystem.SessionNameMenuID].ToString());
            } else {
                if (Session[CacheSystem.SessionNameMenuID] != null && Session[CacheSystem.SessionNameMenuID].ToString() != menuID.ToString()) {
                    cleanFilters = true;
                }

                Session[CacheSystem.SessionNameMenuID] = menuID;
            }
            #endregion

            var allDataModel = Session[CacheSystem.SessionNameAllData] as AllDataModel;

            if (allDataModel == null) {
                refreshData = true;
                allDataModel = new AllDataModel();
            }

            #region MenuFields
            var menuFields = menuLogic.GetMenuFields(menuID);

            var menuListToShow = menuFields
               .Where(x => x.IsMandatory == true)
               .Select(x => x.Alias);

            var databaseMandatoryColumns = menuFields
                .OrderByDescending(x => x.IsMandatory)
                .Select(x => gridLogic.GetColumnName(x.Field, x.Alias));

            var addColumnsDic = menuFields
               .Where(x => x.IsMandatory == false)
               .ToDictionary(x => x.Alias, x => x.Description);

            if (!string.IsNullOrEmpty(addColumns)) {
                var newColumnsToShow = menuFields
                  .Where(x => !string.IsNullOrEmpty(addColumns) && addColumns.Trim().Contains(x.Alias.Trim()))
                  .Select(x => x.Alias);

                menuListToShow = menuListToShow.Union(newColumnsToShow);
            }
            #endregion

            allDataModel.ColumnsToShow = menuListToShow.ToList();
            Session[CacheSystem.SessionNameAllData] = allDataModel;

            if (cleanFilters) {
                filters = string.Empty;
                page = 1;
                sort = string.Empty;
                sortDir = string.Empty;
                addColumns = string.Empty;
            }

            var model = new ProcessDataModel() {
                RefreshData = refreshData,
                ColumnsToShow = menuListToShow.ToList(),
                DatabaseMandatoryColumns = databaseMandatoryColumns.ToList(),
                Filters = string.IsNullOrEmpty(filters) ? new Dictionary<string, string>() : JsonConvert.DeserializeObject<Dictionary<string, string>>(filters),
                MenuFieldsSelected = addColumns,
                MenuFieldsToAdd = addColumnsDic,
                Page = page,
                RequiredFilters = string.IsNullOrEmpty(requiredFilters) ? new Dictionary<string, string>() : JsonConvert.DeserializeObject<Dictionary<string, string>>(requiredFilters),
                Sort = sort,
                SortDir = sortDir,
                SubMenus = ((List<UserPermissionViewPoco>)Session[CacheSystem.SessionNameMenus]).Where(x => x.MenuPrincipalID.HasValue && x.MenuPrincipalID == menuID).ToList(),
                IsSubMenu = isSubMenu
            };

            Session[CacheSystem.SessionNameProcessDataModel] = model;
            var menuInfo = ((List<UserPermissionViewPoco>)Session[CacheSystem.SessionNameMenus]).Where(x => x.MenuID == menuID).FirstOrDefault();

            return RedirectToAction(menuInfo.Action, menuInfo.Controller);
        }
    }
}

M3Light/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@M3Light.Logic.CacheSystem.SoftwareTitle</title>
    <link rel="icon" href="~/Images/logoicon.ico">

    <link rel="stylesheet" type="text/css" href="~/Scripts/">
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Scripts/bootstrap.min.css">

    <script type="text/javascript" language="javascript" src="~/Scripts/modernizr-2.8.3.js"></script>
    <script type="text/javascript">
        window.history.forward();
        function noBack() { window.history.forward(); }
    </script>
</head>
<body onload="noBack();" onpageshow="if (event.persisted) noBack();" onunload="">
    @RenderBody()
</body>
</html>

M3Light/Views/Shared/_MenuLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@M3Light.Logic.CacheSystem.SoftwareTitle</title>
    <link rel="icon" href="~/Images/logoicon.ico">

    <link rel="stylesheet" type="text/css" href="~/Scripts/">
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Scripts/bootstrap.min.css">
    <script type="text/javascript" language="javascript" src="~/Scripts/modernizr-2.8.3.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/bootstrap.min.js"></script>

    <script type="text/javascript">
        var page = 0;
        var totalpages = 0;
        var newPage = 0;
        var sort = '';
        var sortdir = '';

        window.history.forward();
        function noBack() { window.history.forward(); }

        window.addEventListener("load", function () {
            var pageData = document.getElementById("getpage");
            var totalPageData = document.getElementById("gettotalpage");

            if (pageData != null) {
                page = parseInt(pageData.innerHTML);
            }

            if (totalPageData != null) {
                totalpages = parseInt(totalPageData.innerHTML);
            }

            newpage = page;
        });

        function GetUrlToSearch(refreshData = false) {
            if (sortdir == '' && !refreshData) {
                sortdir = GetSortDir(refreshData);
            }

            if (sort == '' && !refreshData) {
                sort = GetSort(refreshData);
            }

            var url = "@Url.Action("ProcessDataMenu", "Core")"
                    + "?menuID=" + '@Session[M3Light.Logic.CacheSystem.SessionNameMenuID]' +
                    "&page=" + newpage +
                    "&sort=" + sort +
                    "&sortDir=" + sortdir +
                    "&refreshData=" + refreshData +
                    "&filters=" + FillFiltersUrl() +
                    "&requiredFilters=" + FillRequiredFiltersUrl() +
                    "&addColumns=" + GetCheckedColumns() +
                    "&isSubMenu=" + GetIsSubMenu();

            window.location.href = url;
        }

        function Refresh() {
            sort = '';
            sortdir = '';
            newpage = 1;
            ClearFilters();
            GetUrlToSearch(true);
        }

        function Search(ignorerequiredFields = null) {
            var requiredFilters = JSON.parse(FillRequiredFiltersUrl());

            if (ignorerequiredFields != null) {
                ignorerequiredFields.forEach(key => delete requiredFilters[key]);
            }

            var newRequiredFilters = JSON.stringify(requiredFilters);

            if (!newRequiredFilters.includes(':""') &&
                !newRequiredFilters.includes('<->"') &&
                !newRequiredFilters.includes('"<->')) {
                Refresh();
            }
        }

        // --------------------------------Begin Filters--------------------------------
        function GetCheckedColumns() {
            var text = ''
            var inputs = document.querySelectorAll("input[type='checkbox']");
            for (var i = 0; i < inputs.length; i++) {
                if (inputs[i].checked == true) {
                    text += inputs[i].id + ",";
                }
            }

            var lastChar = text.substr(text.length - 1);

            if (lastChar == ',') {
                text = text.substring(0, text.length - 1);
            }

            return text;
        }

        function dropdownSearch() {
            document.getElementById("dropdownSearch").classList.toggle("show");

            var buttonId = document.getElementById("dropdowncolumnsbutton");
            if (buttonId.disabled) {
                buttonId.disabled = false;
            } else {
                buttonId.disabled = true;
            }
        }

        function dropdownColumns() {
            document.getElementById("dropdownColumns").classList.toggle("show");

            var buttonId = document.getElementById("dropdownsearchbutton");
            if (buttonId.disabled) {
                buttonId.disabled = false;
            } else {
                buttonId.disabled = true;
            }
        }

        function BetweenValues(deInput, ateInput) {
            var de = deInput == null ? '' : deInput.value;
            var ate = ateInput == null ? '' : ateInput.value;
            var result = de != '' || ate != '' ? de + "<->" + ate : '';

            return result;
        }

        function inputValue(inputValue) {
            return inputValue == null ? '' : inputValue.value.trim();
        }

        function clearValue(inputValue) {
            if (inputValue != null) {
                inputValue.value = '';
            }
        }

        function clearCheckBoxs() {
            var inputs = document.querySelectorAll("input[type='checkbox']");

            if (inputs != null) {
                for (var i = 0; i < inputs.length; i++) {
                    inputs[i].checked = false;
                }
            }
        }

        function CheckCheckBoxs(value) {
            var inputs = document.querySelectorAll("input[type='checkbox']");
            for (var i = 0; i < inputs.length; i++) {
                if (value.includes(inputs[i].id)) {
                    inputs[i].checked = true;
                }
            }
        }

        function OnLoadFilters(filters, deInput = '', ateInput = '') {
            $.each(filters, function (key, value) {
                if (document.getElementById(key) != null) {
                    document.getElementById(key).value = value;
                } else {
                    if (value.includes('<->')) {
                        var split = value.split("<->");

                        document.getElementById(deInput).value = split[0];
                        document.getElementById(ateInput).value = split[1];
                    }
                }
            });
        }
        // --------------------------------End Filters--------------------------------

        // --------------------------------Begin Pagination--------------------------------
        function firstPage() {
            newpage = 1;
            GetUrlToSearch();
        };

        function lastPage() {
            newpage = totalpages;
            GetUrlToSearch();
        };

        function previousPage() {
            newpage = page - 1;
            GetUrlToSearch();
        };

        function nextPage() {
            newpage = page + 1;
            GetUrlToSearch();
        };
        // --------------------------------End Pagination--------------------------------


        // --------------------------------Begin Sort--------------------------------
        function SortClick(lastsort, lastsortdir, newsort) {
            if (lastsort == newsort) {
                sort = newsort;

                if (lastsortdir == 'asc') {
                    sortdir = 'desc';
                } else {
                    sortdir = 'asc';
                }
            } else {
                sort = newsort;
                sortdir = 'asc';
            }

            GetUrlToSearch();
        }
        // --------------------------------End Sort--------------------------------
    </script>
</head>
<body onload="noBack();" onpageshow="if (event.persisted) noBack();" onunload="">
    <div id="header" class="header-small">
        <div id="headerimagediv" class="headerimgdiv">
            <img src="~/Images/logo.png" height="40" width="140">
        </div>

        <div id="headertitleMenudiv" class="headertitleMenudiv">
            @M3Light.Logic.CacheSystem.SoftwareTitle
        </div>

        <div id="headertitleUserdiv" class="headertitleUserdiv">
            Sessão : @Session[M3Light.Logic.CacheSystem.SessionNameUsername].ToString() || <span class="ahref" onclick="location.href='@Url.Action("Logout", "Login")'"> Terminar Sessão </span>
        </div>
    </div>

    <div id="content" class="divcontent">
        <div id="left" class="menulayoutleft">
            <div id='cssmenu' class="menusize">
                <ul>
                    @{
                        var listMenus = (List<M3Light.Models.UserPermissionViewPoco>)Session["Menus"];

                        var menuID = Session[M3Light.Logic.CacheSystem.SessionNameMenuID];

                        var isSubMenu = string.Empty;
                        if (menuID != null) {
                            isSubMenu = listMenus.Where(x => x.MenuID.ToString() == menuID.ToString()).Select(x => x.MenuPrincipalID.ToString()).FirstOrDefault();
                        }

                        foreach (var menu in (List<M3Light.Models.UserPermissionViewPoco>)Session["Menus"]) {
                            if (menu.ShowInMainMenu) {
                                if (menuID != null &&
                                    ((menuID.ToString() == menu.MenuID.ToString() && menu.ShowInMainMenu) ||
                                    (menu.MenuID.ToString() == isSubMenu.ToString() && !menu.ShowInMainMenu))) {
                                    <li class="selected">
                                        <a href="@Url.Action("ProcessDataMenu", "Core", new { menuID = menu.MenuID, refreshData = true })"><span>@menu.Menu</span></a>
                                    </li>
                                } else {
                                    <li>
                                        <a href="@Url.Action("ProcessDataMenu", "Core", new { menuID = menu.MenuID, refreshData = true })"><span>@menu.Menu</span></a>
                                    </li>
                                }
                            }
                        }
                    }
                </ul>
            </div>
            <div id="footer" class="menufooter">
                <a target="_blank" href="https://icons8.com/icons/set/list--v1">List icon</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
            </div>
        </div>

        <div id="right" class="menulayoutright">
            <div id="contentgrid" class="contentgrid">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

M3Light/Views/Shared/_PartialPageAddColumns.cshtml
@model M3Light.Models.GridTableModel

@if (Model.DataToShow != null && Model.MenuFieldsToAdd.Count > 1) {
    <div id="dropdowncolumnsbutton" class="btn btn-sm buttonfilter" onclick="dropdownColumns()">
        <img src="~/Images/filter.png" height="15" width="15">
        Adicionar colunas
    </div>

    <div id="dropdownColumns" class="dropdown-content">
        @foreach (var column in Model.MenuFieldsToAdd) {
            <div class="addcolumnsdiv">
                <input type="checkbox" id="@Html.Raw(column.Key)" name="@Html.Raw(column.Key)" value="@Html.Raw(column.Value)">
                <label class="searchaddcolumnstext" for="@Html.Raw(column.Key)"> @Html.Raw(column.Value)</label>
            </div>
        }

        <div class="buttondivfilters">
            <button class="btn btn-default btn-sm" onclick="GetUrlToSearch()"> Pesquisar</button>
        </div>
    </div>
}

M3Light/Views/Shared/_PartialPageBackMenuPrincipal.cshtml
@model M3Light.Models.GridTableModel

@{
    var menus = (List<M3Light.Models.UserPermissionViewPoco>)Session[M3Light.Logic.CacheSystem.SessionNameMenus];
    var menuPrincipalID = menus.Where(x => x.MenuID.ToString() == Session[M3Light.Logic.CacheSystem.SessionNameMenuID].ToString()).FirstOrDefault().MenuPrincipalID;
    var filtersJson = Newtonsoft.Json.JsonConvert.SerializeObject(Model.RequiredFilters);

    <div class="btn btn-sm gridbuttons buttonfilter backbutton" onclick="location.href='@Url.Action("ProcessDataMenu", "Core", new { menuID = menuPrincipalID, refreshData = true, requiredFilters = filtersJson })'">
        <img src="~/Images/back.png" height="15" width="15">
        Voltar
    </div>
}

M3Light/Views/Shared/_PartialPageButtonsOptions.cshtml
@model M3Light.Models.GridTableModel

@if (Model.DataToShow != null) {
    <div class="btn btn-sm gridbuttons buttonfilter gridbuttonsright" onclick="Refresh()">
        <img src="~/Images/refresh.png" height="15" width="15">
        Voltar a Carregar Dados
    </div>

    <div class="btn btn-sm gridbuttons buttonfilter gridbuttonsright" onclick="location.href='@Url.Action("Export", "Core",  new { sessionName = M3Light.Logic.CacheSystem.SessionNameAllData })'">
        <img src="~/Images/export.png" height="15" width="15">
        Exportar
    </div>

    <div class="btn btn-sm gridbuttons buttonfilter gridbuttonsright" onclick="location.href='@Url.Action("Export", "Core",  new { sessionName = M3Light.Logic.CacheSystem.SessionNamePartialData })'">
        <img src="~/Images/exportfilters.png" height="15" width="20">
        Exportar c/ filtro
    </div>
}

M3Light/Views/Shared/_PartialPageTable.cshtml
@model M3Light.Models.GridTableModel

@if (Model.DataToShow != null) {
    <div class="griddata">
        <table class="table table-sm table-bordered table-hover" style="font-size: 12px;cursor: pointer;">
            <thead class="tablehead">
                <tr>
                    @{
                        if (Model.SubMenus.Count > 0) {
                            <th></th>
                        }

                        foreach (System.Data.DataColumn column in Model.DataToShow.Columns) {
                            if (column.ColumnMapping != System.Data.MappingType.Hidden) {
                                if (Model.Sort == column.ColumnName) {
                                    <th onclick="SortClick('@Model.Sort','@Model.SortDir','@column.ColumnName')">
                                        @if (Model.SortDir == "asc") {
                                            <img src="~/Images/sort-asc.png" height="15" width="15">
                                        } else {
                                            <img src="~/Images/sort-desc.png" height="15" width="15">
                                        }

                                        @column.ColumnName
                                    </th>
                                } else {
                                    <th onclick="SortClick('@Model.Sort','@Model.SortDir','@column.ColumnName')">@column.ColumnName</th>
                                }
                            }
                        }
                    }
                </tr>
            </thead>

            <tbody>
                @{
                    foreach (System.Data.DataRow row in Model.DataToShow.Rows) {
                        <tr>
                            @if (Model.SubMenus.Count > 0) {
                                <td>
                                    <div class="dropdown">
                                        <button class="dropdownMenu1-cssbutton" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            <img src="~/Images/submenu.png" height="20" width="20">
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            @foreach (var submenu in Model.SubMenus) {
                                                var filters = new Dictionary<string, string>();

                                                foreach (var subMenuFilter in submenu.Filters) {
                                                    if (Model.RequiredFilters.ContainsKey(subMenuFilter)) {
                                                        filters.Add(subMenuFilter, Model.RequiredFilters[subMenuFilter]);
                                                    } else {
                                                        filters.Add(subMenuFilter, row[subMenuFilter].ToString());
                                                    }
                                                }

                                                var filtersJson = Newtonsoft.Json.JsonConvert.SerializeObject(filters);

                                                <li>
                                                    <a href="@Url.Action("ProcessDataMenu","Core", new { menuID = submenu.MenuID, refreshData = true, requiredFilters = filtersJson, isSubMenu = true })">@submenu.MenuName</a>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </td>
                            }

                            @foreach (System.Data.DataColumn column in Model.DataToShow.Columns) {
                                if (column.ColumnMapping != System.Data.MappingType.Hidden) {
                                    <td>@row[column].ToString()</td>
                                }
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

    <div id="pagination" class="gridpagination">
        <div id="paginationbuttons" class="gridpaginationbuttons">
            @*Paginação feita aquando da criação porque alterar para disabled em javascript provoca delay*@
            @if ((Model.Page == 1 || Model.Page == 0) && Model.Page == Model.TotalPages) {
                <button id="firstpage" class="buttonpagination" onclick="firstPage()" disabled>
                    &laquo;
                </button>
                <button id="previouspage" class="buttonpagination" onclick="previousPage()" disabled>&lt;</button>
                <button id="nextpage" class="buttonpagination" onclick="nextPage()" disabled>&gt;</button>
                <button id="lastpage" class="buttonpagination" onclick="lastPage()" disabled>&raquo;</button>
            } else if (Model.Page == 1) {
                <button id="firstpage" class="buttonpagination" onclick="firstPage()" disabled>&laquo;</button>
                <button id="previouspage" class="buttonpagination" onclick="previousPage()" disabled>&lt;</button>
                <button id="nextpage" class="buttonpagination" onclick="nextPage()">&gt;</button>
                <button id="lastpage" class="buttonpagination" onclick="lastPage()">&raquo;</button>
            } else if (Model.Page == Model.TotalPages) {
                <button id="firstpage" class="buttonpagination" onclick="firstPage()">&laquo;</button>
                <button id="previouspage" class="buttonpagination" onclick="previousPage()">&lt;</button>
                <button id="nextpage" class="buttonpagination" onclick="nextPage()" disabled>&gt;</button>
                <button id="lastpage" class="buttonpagination" onclick="lastPage()" disabled>&raquo;</button>
            } else {
                <button id="firstpage" class="buttonpagination" onclick="firstPage()">&laquo;</button>
                <button id="previouspage" class="buttonpagination" onclick="previousPage()">&lt;</button>
                <button id="nextpage" class="buttonpagination" onclick="nextPage()">&gt;</button>
                <button id="lastpage" class="buttonpagination" onclick="lastPage()">&raquo;</button>
            }
        </div>

        <div class="gridpaginationsbuttonstext">
            <span id="getpage">@Model.Page</span>
            <span> de </span>
            <span id="gettotalpage">@Model.TotalPages</span>
            <span> páginas</span>
        </div>
    </div>
}